# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf


# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/workspaces.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu
windowrule = workspace 10 silent, match:title ^(MusicPulse)$
windowrule = workspace 10 silent, match:title ^(MusicLyrics)$
windowrule = workspace 10 silent, match:class ^(com.mitchellh.ghostty)$, match:title ^(MusicDashboard)$
windowrule = workspace 10 silent, match:class ^(com.mitchellh.ghostty)$, match:title ^(MusicVisualizer)$
windowrule = float on, match:title ^(MusicPulse)$
windowrule = float on, match:title ^(MusicLyrics)$
windowrule = float on, match:title ^(MusicDashboard)$
windowrule = float on, match:title ^(MusicVisualizer)$
windowrule = no_initial_focus on, match:title ^(MusicPulse)$
windowrule = no_initial_focus on, match:title ^(MusicLyrics)$
windowrule = no_initial_focus on, match:title ^(MusicDashboard)$
windowrule = size 1080 1030, match:title ^(MusicVisualizer)$
windowrule = move 12 38, match:title ^(MusicVisualizer)$
windowrule = size 804 280, match:title ^(MusicPulse)$
windowrule = move 1104 38, match:title ^(MusicPulse)$
windowrule = size 804 500, match:title ^(MusicLyrics)$
windowrule = move 1104 330, match:title ^(MusicLyrics)$
windowrule = size 804 226, match:title ^(MusicDashboard)$
windowrule = move 1104 842, match:title ^(MusicDashboard)$
windowrule = workspace 110 silent, match:class ^(spotify)$
